apiVersion: v1
kind: Service
metadata:
  name: udacity-aws-devops-capstone-project-service
  namespace: udacity-aws-devops-capstone-project
  labels:
    app: udacity-aws-devops-capstone-project
spec:
  selector:
    app: udacity-aws-devops-capstone-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer