version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  install-aws-cli:
    description: Install AWS CLI
    steps:
      - aws-cli/install
      - aws-cli/setup
  
  install-ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt update
            sudo apt install -y ansible

jobs:
  lint:
    docker:
      - image: alpine:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update --no-cache make
            make install
      - run:
          name: run lint
          command: |
            make lint
  
  build_docker_image:   
    docker:
      - image: cimg/python:3.7
    steps:
      - install-aws-cli
      - install-ansible
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "44:6f:bb:68:d8:89:a9:bb:46:85:08:01:57:39:e2:38"
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            echo $PROVISIONING_SERVER_HOST >> .circleci/ansible/inventory.txt
      - run:
          name: Copy Dockerfile
          command: |
            cp Dockerfile .circleci/ansible/roles/build-docker-image/files/Dockerfile
      - run:
          name: Build and Push Docker image
          command: |
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is -------"
            cat inventory.txt
            ansible-playbook -i inventory.txt build-docker-image.yml

workflows:
  default:
    jobs:
      - lint
      - build_docker_image:
          requires: [lint]