- name: "Docker login"
  shell: |
    docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

- name: "Update kubectl config to use AWS EKS Cluster"
  shell: |
    aws eks update-kubeconfig \
      --region $AWS_DEFAULT_REGION \
      --name Udacity

- name: "Set up  Kubctl context"
  shell: |
    kubectl config set-context --current --namespace=udacity-aws-devops-capstone-project

- name: "Deploy latest image"
  shell: |
    kubectl set image deployment.apps/udacity-aws-devops-capstone-project-deployment nginx=$DOCKERHUB_REPOSITORY:$CIRCLE_WORKFLOW_ID -n udacity-aws-devops-capstone-project